top_xpath = "//chapter[@id='chapter-building-system']//sect1[.//productname]"

[fields]
pkgname = ".//productname/text()"
#pkgver = ".//productnumber/text()"
#build_commands = ".//screen[not(@role=\"nodump\")]//userinput//text()"
#source = "./ancestor::book//sect1[@id='ch-materials-packages']//para[contains(.,'Download:')]/ulink/@url"
