# ================================================================
# Scripter Configuration
# ================================================================

[main]
parser_output = "builder/build/books/{book}/parser/build_metadata/"
script_dir = "builder/build/books/{book}/scripter/scripts/"
default_template = "template.script"

[global]
regex = []

[chapter-cross-tools]
template = "chapter-temp-tools.script"

[chapter-temporary-tools]
template = "chapter-temp-tools.script"

[chapter-chroot-temporary-tools]
template = "chapter-chroot-tools.script"


#------------------------------------------------------------------#
# FILTERS
#------------------------------------------------------------------#

[chapter_filters]
include  = [ "chapter-cross-tools", "chapter-temporary-tools", "chapter-chroot-temporary-tools" ]
exclude  = []

[section_filters]
include  = []
exclude  = [ "ch-tools-introduction" ]

[package_filters]
include = []
exclude = []
deps    = []

