# ================================================================
# Scripter Configuration
# ================================================================

[main]
parser_output = "builder/build/{book}/parser/build_metadata/"
script_dir = "builder/build/{book}/{profile}/scripter/scripts/"
default_template = "template.script"

[global]
regex = []

[ch-tools-changingowner]
template = "ch-tools-changingowner.script"

[ch-tools-creatingdirs]
template = "ch-tools-creatingdirs.script"

[ch-tools-createfiles]
template = "ch-tools-createfiles.script"

#------------------------------------------------------------------#
# FILTERS
#------------------------------------------------------------------#

[chapter_filters]
include  = [ "chapter-chroot-temporary-tools" ]
exclude  = []

[section_filters]
include  = []
exclude  = [ "ch-tools-introduction-chroot", "ch-tools-kernfs", "ch-tools-chroot" ]

[package_filters]
include = []
exclude = []
deps    = []

