# ================================================================
#
# Scripter Configuration
#
# ================================================================

[main]
parser_output = "builder/build/{book}/parser/build_metadata/"
script_dir = "builder/build/{book}/{profile}/scripter/scripts/"
default_template = "template.script"

[global]
regex = []


#------------------------------------------------------------------#
# OVERRIDES
#------------------------------------------------------------------#

[ch-materials-introduction]
template = "ch-materials-introduction.script"
regex = [ 
		"r@(?s)wget --input-file.*?.*\\$LFS/sources/\\*\\n?@@",
		"s@mkdir@[ -d \"$LFS/sources\" ] || sudo mkdir@",	
		"s@chmod@sudo chmod@",	
 ]

[ch-materials-packages]
template = "ch-materials-packages.script"

[ch-materials-patches]
template = "ch-materials-patches.script"
regex = [ "r@done@done\n\nchown root:root $LFS/sources/*@" ]


#------------------------------------------------------------------#
# FILTERS
#------------------------------------------------------------------#

[chapter_filters]
include  = [ "chapter-getting-materials" ]
exclude  = []

[section_filters]
include  = []
exclude  = []

[package_filters]
include = []
exclude = []
deps    = []
