# ================================================================
# Scripter Configuration
# ================================================================

[main]
parser_output = "builder/build/{book}/parser/build_metadata/"
script_dir = "builder/build/{book}/{profile}/scripter/scripts/"
default_template = "template.script"

[global]
regex = []

[chapter-final-preps]
template = "chapter-final-preps.script"

[ch-preps-settingenviron]
template = "ch-preps-settingenviron.script"


#------------------------------------------------------------------#
# FILTERS
#------------------------------------------------------------------#

[chapter_filters]
include  = [ "chapter-final-preps" ]
exclude  = []

[section_filters]
include  = []
exclude  = [ "ch-preps-introduction", "ch-preps-aboutsbus", "ch-preps-abouttestsuites" ]

[package_filters]
include = []
exclude = []
deps    = []

