# ================================================================
# Scripter Configuration
# ================================================================

[main]
parser_output = "builder/build/{book}/parser/build_metadata/"
script_dir = "builder/build/{book}/{profile}/scripter/scripts/"
default_template = "template.script"

[global]
regex = []

[chapter-final-preps]
template = "chapter-final-preps.script"
regex =	[
	    "s@groupadd lfs@getent group lfs >/dev/null || groupadd lfs@",
	    "r@(useradd.*)@id -u lfs >/dev/null 2>&1 || \\1@"
	]  

[ch-preps-settingenviron]
template = "ch-preps-settingenviron.script"
regex = [ "s@$(uname -m)@\\$(uname -m)@", 
	  "s@$PATH@\\$PATH@",
	  "s@$LFS/@\\$LFS/@",
	  "s@$(nproc)@\\$(nproc)@" 
	]


#------------------------------------------------------------------#
# FILTERS
#------------------------------------------------------------------#

[chapter_filters]
include  = [ "chapter-final-preps" ]
exclude  = []

[section_filters]
include  = []
exclude  = [ "ch-preps-introduction", "ch-preps-aboutsbus", "ch-preps-abouttestsuites" ]

[package_filters]
include = []
exclude = []
deps    = []

