[package_aliases]
bind-utils = "bind_utilities"
cyrus-sasl = "cyrus_sasl"
DocBook = "docbook-xml"
freetype2 = "freetype"
glib2 = "glib"
gnupg2 = "gnupg"
gtk3 = "gtk"
hatch-vcs = "hatch_vcs"
java-bin = "java"
libXau = "libxau"
Links = "links"
Mako = "mako"
mitkrb = "mit_kerberos_v5"
pypa-build = "build"
pyproject-hooks = "pyproject_hooks"
python3 = "python"
PyYAML = "pyyaml"
qt6 = "qt"
tl-installer = "install-tl"
xorg-env = "xorg-server"
xorg7-app = "xorg_applications"
xorg7-font = "xorg_fonts"
xorg7-lib = "xorg_libraries"
x-window-system = "xinit"