[package_aliases]
bind-utils = "bind_utilities"
DocBook = "docbook-xml"
freetype2 = "freetype"
glib2 = "glib"
gnupg2 = "gnupg"
gtk3 = "gtk"
hatch-vcs = "hatch_vcs"
java-bin = "java"
mitkrb = "mit_kerberos_v5"
pypa-build = "build"
pyproject-hooks = "pyproject_hooks"
python3 = "python"
qt6 = "qt"
tl-installer = "install-tl"
xorg7-lib = "xorg_libraries"
x-window-system = "xinit"