[package_aliases]
bind-utils = "bind_utilities"
cyrus-sasl = "cyrus_sasl"
dejavu-fonts = ""
DocBook = "docbook-xml"
docbook-xsl = "docbook-xsl-nons"
freetype2 = "freetype"
glib2 = "glib"
gnupg2 = "gnupg"
gtk3 = "gtk"
gtk4 = "gtk"
hatch-vcs = "hatch_vcs"
kf6-frameworks = ""
java-bin = "java"
libevdev = "libevdev_1.13.4"
libXau = "libxau"
libXdmcp ="libxdmcp"
Links = "links"
Mako = "mako"
mitkrb = "mit_kerberos_v5"
plasma-build = "plasma-activities"
pygobject3 = "pygobject"
pypa-build = "build"
pyproject-hooks = "pyproject_hooks"
python3 = "python"
PyYAML = "pyyaml"
sc-jquery = "sphinxcontrib-jquery"
qt6 = "qt"
rust = "rustc"
tl-installer = "install-tl"
xcb-utilities = "xcb-util"
xkeyboard-config = "xkeyboardconfig"
xorg-env = ""
xorg-libinput-driver = "xorg_libinput_driver"
xorg7-app = "xorg_applications"
xorg7-font = "xorg_fonts"
xorg7-legacy = "xorg_legacy"
xorg7-lib = "xorg_libraries"
xterm2 = "xterm"
x-window-system = "xinit"