[aliases]
DocBook = "docbook-xml-4.5"
docbook-xsl = "docbook-xsl-nons-1.79.2"
freetype2 = "freetype-2.13.3"
glib2 = "glib-2.84.4"
rust = "rustc-1.89.0"
xkeyboard-config = "xkeyboardconfig-2.45"
xorg-env = ""
xorg7-app = "xorg_applications-_version_"
xorg7-font = "xorg_fonts-_version_"
xorg7-lib = "xorg_libraries-_version_"