[aliases]
DocBook = "docbook-xml-4.5"
docbook-xsl = "docbook-xsl-nons-1.79.2"
freetype2 = "freetype-2.13.3"
glib2 = "glib-2.84.4"
xorg-env = ""
xorg7-font = "xorg_fonts-_version_"
xorg7-lib = "xorg_libraries-_version_"