[package_aliases]
bind-utils = "bind_utilities"
freetype2 = "freetype"
hatch-vcs = "hatch_vcs"
mitkrb = "mit_kerberos_v5"
pypa-build = "build"
pyproject-hooks = "pyproject_hooks"
python3 = "python"
xorg7-lib = "xorg_libraries"
x-window-system = "xinit"